### ISSUE TITLE
Reduce Final MP4 Size

### ISSUE THREAD

**Issue by navkumar987** [manishkatyan/bbb-mp4#10]
Hi Manish,

Scripts are working well. But the final output mp4 size is too large.
When I have used https://github.com/jibon57/bbb-recorder, 2 Hour video would come around 200 Mb Maximum, Now the Same video is going upto 800mb.

Kindly update your ffmpeg command to reduce the final output size

**Comment by manishkatyan** [comment]
Hi @navkumar987 Thanks for your feedback. We will see how to reduce file size.
