### ISSUE TITLE
mp4 file remains on the server after deleting the recording in greenlight

### ISSUE THREAD

**Issue by roman-suru** [manishkatyan/bbb-mp4#11]
I fixed it by assigning the default mp4 dir to : 

`mp4_dir = /var/bigbluebutton/published/presentation`

So if a user deletes the recording in Greenlight, he also deletes the mp4.
Then I changed the last line in bbb_mp4.sh to: 

`ffmpeg -nostdin -y -i "$webm_dir"/"$meeting_id".webm -c:v libx264 -preset veryfast -movflags faststart -profile:v high -level 4.2 -max_muxing_queue_size 9999  -vf mpdecimate -vsync vfr "$mp4_dir"/"$meeting_id"/"recording.mp4`

But then I can't access the mp4 file from the url anymore. Any idea how to redirect to the new file location?

Great Tool, thank you a lot!

**Comment by roman-suru** [comment]
Nevermind, I fixed it by assigning  `var new_url = "/presentation/" + meeting_id + "/recording.mp4";` in the playback.html

Should I close this issue or even make a pull request?

**Comment by manishkatyan** [comment]
@BackfischHunter Glad that it worked!
