### ISSUE TITLE
Remove right white panel, when no webcams were recorded.

### ISSUE THREAD

**Issue by roman-suru** [manishkatyan/bbb-mp4#12]
![Screenshot 2021-02-26 104731](https://user-images.githubusercontent.com/46672071/109284360-0ef29e80-7820-11eb-9a46-b025d7e166a4.png)

Also, do you know a way to increase quality in the deskshare? 
text is sometimes hard to read.

**Comment by manishkatyan** [comment]
Hi,

I am not sure if I get your issue correctly or how it's related to bbb-mp4 extension.
