### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by Korney99** [manishkatyan/bbb-mp4#16]
Hi!
thank You very mutch for your work ))
I have a two questions:
1. I`s installd BBB-MP4 about two mounth ago, but now exixst a new version. What must I do for update my BBB-MP4 to lasted version?
2. Can I to convert my old video in BBB to mp4 via  BBB-MP4?
Thank You again!

**Comment by arun-hel** [comment]
@Korney99  

1. You can simply install it again ,This is fully dockerized so no need to worry about anything.
2. You can convert existing recording to mp4 by running `sh bbb-mp4.sh meetingID`

**Comment by Korney99** [comment]
Thank`s for your help )).
