### ISSUE TITLE
scalelite aws bigbluebutton setup problem

### ISSUE THREAD

**Issue by nzmhtpgl** [manishkatyan/bbb-mp4#17]
First of all thank you very much for this usefull app. i wonder that can i install it scalelite bbb system? if yes how?
Because you know that in scalelite bbb scalelite ec2 copies all presentation to itself. So where should i install this app bbbstack or scalelite stack? i confused.

**Comment by arun-hel** [comment]
@nzmhtpgl  Yes you can install bbb-mp4 for  scalelite setup but its a bit tricky. You have to create a new folder in `/mnt/scalelite-recordings/var/bigbluebutton/`. Then you can install bbb-mp4 on bbb server as usual and change .env COPY_TO_LOCATION to the folder you just created also you have to mount this  folder to nginx container if using scalelite docker setup and create location derivative for nginx . Rename default playback.html to playback_default.html and create new  [playback.html](https://raw.githubusercontent.com/manishkatyan/bbb-mp4/main/playback.html) .Thats it this is how we are using bbb-mp4 with scalelite. By the way AWS setup may [cost](https://higheredlab.com/bbb-tools/) you more we have experienced it.

**Comment by manishkatyan** [comment]
Closing as no response from the user
