### ISSUE TITLE
 Over two hours and video quality

### ISSUE THREAD

**Issue by Korney99** [manishkatyan/bbb-mp4#18]
Hi Thank You for Your work )).
I`s installd а new version. All work is OK but only if a conference about two hours duration.
If a conference lasts more than two hours, mp4 file is created, but it`s broken.
What can I do to extend processing time for mp4 file?
And one more question:
How can I to change quolity video in mp4 file?

Thank You again.

**Comment by Korney99** [comment]
The Size of mp4 file - 498699 KB
journalctl -t bbb-mp4 answer: "-- No entries --" ((.

**Comment by arun-hel** [comment]
@Korney99  can you convert it by running `sh bbb-mp4.sh meetingID` ? use different meeting id .

**Comment by Korney99** [comment]
Excuse me, do not quite understand...
Broken record is ID 3b1865ff3325ac65dcec8ac6428156c5f50b3346-1616929221539
Must I to run sh bbb-mp4.sh 3b1865ff3325ac65dcec8ac6428156c5f50b3346-1616929221539 ?

**Comment by arun-hel** [comment]
@Korney99 Remove broken mp4  and try `sh bbb-mp4.sh 3b1865ff3325ac65dcec8ac6428156c5f50b3346-1616929221539`
make sure you have correct .env . Try sudo journalctl -t bbb-mp4 for logs

**Comment by arun-hel** [comment]
As soon as you run `sh bbb-mp4.sh 3b1865ff3325ac65dcec8ac6428156c5f50b3346-1616929221539 `one docker container will start and container name will be meeting id. you can see logs by running `docker logs 3b1865ff3325ac65dcec8ac6428156c5f50b3346-1616929221539 -f`

**Comment by Korney99** [comment]
Hm...
sh bbb-mp4.sh 3b1865ff3325ac65dcec8ac6428156c5f50b3346-1616929221539
Answer: 0cdaec7708d14cca92c1df2438a4828c26a36ed90a957af65d852ad1ed99730a
sudo journalctl -t bbb-mp4
Answer:  converting 3b1865ff3325ac65dcec8ac6428156c5f50b3346-1616929221539 to mp4
docker logs 3b1865ff3325ac65dcec8ac6428156c5f50b3346-1616929221539 -f
Answer: Error: No such container: 3b1865ff3325ac65dcec8ac6428156c5f50b3346-1616929221539

**Comment by arun-hel** [comment]
what is your env?
`
playbackFile=playback_default.html
BBB_DOMAIN_NAME=bbb.yourdomain.com
COPY_TO_LOCATION=/var/www/bigbluebutton-default/recording`
it should look like this.

**Comment by Korney99** [comment]
In "/var/www/bbb-mp4"
File ".env"
playbackFile=playback_default.html
BBB_DOMAIN_NAME=con.aesol.ru
COPY_TO_LOCATION=/var/www/bigbluebutton-default/recording

Greenlight is ON

**Comment by Korney99** [comment]
I think maybe it`s not a problem bbb-mp4?
Maybe the matter is in the server settings about filesize...
But I have no idea what is the settings ((.
And why don`t work bbb-mp4.sh for old records...

**Comment by arun-hel** [comment]
`https://YOUR.BBB.DOMAIN/playback/presentation/2.0/playback_default.html?meetingId=MEETING_ID`
you should be able to see recording playback . if you get error then installation is not completed . please go through : https://github.com/manishkatyan/bbb-mp4#install 

you can start manually  docker container without -d so you will see the logs ,
`sudo docker run --rm --name 3b1865ff3325ac65dcec8ac6428156c5f50b3346-1616929221539 -v /var/www/bigbluebutton-default/recording:/usr/src/app/download --env-file .env --env REC_URL=https://BBB.YOURE.DOMAIN/playback/presentation/2.0/playback_default.html?meetingId=MEETING_ID bbb-mp4:v1`

**Comment by Korney99** [comment]
Oh my... I have no file "playback_default.html" In "/var/bigbluebutton/playback/presentation/2.0/"
only "playback.html"
So, link "https://YOUR.BBB.DOMAIN/playback/presentation/2.0/playback_default.html?meetingId=MEETING_ID" do not work, but
link "https://YOUR.BBB.DOMAIN/playback/presentation/2.0/playback.html?meetingId=MEETING_ID" worked is OK...
I think, I need to reinstall bbb-mp4, but I can to do it only after Sunday.
Can I ask You again later?
Thank for You help!

**Comment by Korney99** [comment]
And, exuse me for my bad English ((.

**Comment by arun-hel** [comment]
@Korney99  yes you need to reinstall (be sure to follow all installation instructions for automatic mp4 conversation).  You can ask if you get any issue.

**Comment by Korney99** [comment]
Don`t close this thread yet please, I`l test BBB+bbb-mp4 on different server.
Thank You.

**Comment by arun-hel** [comment]
@Korney99 let us known your status, we have to close the thread if it became inactive..

**Comment by Korney99** [comment]
Now recording 3th-hours conference. 
Short mp4 files generated sucseeful.

**Comment by Korney99** [comment]
OK! All work.
Thank You.
