### ISSUE TITLE
Not Working with ubuntu 18.04 that is running the latest BigBlueButton 2.3

### ISSUE THREAD

**Issue by HasanMajhali** [manishkatyan/bbb-mp4#19]
Not Working with ubuntu 18.04 that is running the latest BigBlueButton 2.3
the BigBlueButton 2.3 Only has index.html at the 
/var/bigbluebutton/playback/presentation/2.3

**Comment by arun-hel** [comment]
@HasanMajhali  We are working on making bbb-mp4 for bbb-2.3

**Comment by arun-hel** [comment]
@HasanMajhali We have updated bbb-mp4 for  bbb 2.3 you can install it now.

**Comment by arun-hel** [comment]
@HasanMajhali  We updated bbb-mp4, Now you can convert BigBlueButton 2.3 recordings to mp4.
