### ISSUE TITLE
VARIABLE ERROR TYPE

### ISSUE THREAD

**Issue by fa305757** [manishkatyan/bbb-mp4#24]
The error of type of undefined variable does not allow the visualization of the download button.
![Schermata del 2021-06-01 11-58-54](https://user-images.githubusercontent.com/24512817/120306371-17042380-c2d2-11eb-8e90-cbb8d11946d9.png)

**Comment by arun-hel** [comment]
If you are using chrome try Hold down the ctrl key and left-click the Reload button
If you are using firefox try Hold down the shif key and left-click the Reload button
This bypass the cache to refresh possibly outdated or corrupted files

**Comment by fa305757** [comment]
I follow your advice but with same result, also to another PC

**Comment by arunkumar141997** [comment]
We couldn't reproduce this error. It looks like browser cache issue.Do you see download button on mobile browser?
Can you try with another video? or may be open this video  in private window.

**Comment by arun-hel** [comment]
@fa305757  We are working on this issue, we will update the code soon,
