### ISSUE TITLE
After update to BBB 2.3.3 player stop to work

### ISSUE THREAD

**Issue by fa305757** [manishkatyan/bbb-mp4#25]
After updating to BBB version 2.3.3 the player shows a blank page preventing you from viewing the default BBB recordings and the recordings are not converted into mp4 files.

**Comment by arun-hel** [comment]
@fa305757  we will fix this soon. You can refer https://github.com/manishkatyan/bbb-mp4#uninstall to revert back to default version of bigbluebutton playback.

**Comment by fa305757** [comment]
I have already performed the restore procedure and the player works correctly. Thank you very much
