### ISSUE TITLE
Conversion status of the file to download

### ISSUE THREAD

**Issue by fa305757** [manishkatyan/bbb-mp4#27]
Meanwhile, I would like to thank you for the two problems solved in a brilliant way. But I ask you if you can make some corrections to the download button so that it can indicate, perhaps by changing the colour of the 'download' text, when the system has finished converting the video to mp4 format. In fact, if you try to press the button before the conversion has been completed, the browser window opens, indicating a file format that cannot be interpreted.
Yours sincerely

**Comment by arun-hel** [comment]
@fa305757  Thanks for using our bbb-mp4, Currently we don't have any plans for that but we may add this in future.
