### ISSUE TITLE
Restrict Automatic Recording for Specific Rooms

### ISSUE THREAD

**Issue by navkumar987** [manishkatyan/bbb-mp4#28]
Can we do something like Restrict Automatic Recording for Specific Rooms, Room IDs could be stored in a file and for those, the recording script should be intiated.

Thanks,

**Comment by arun-hel** [comment]
@navkumar987 We have customized [Greenlight](https://class.higheredlab.com/). you can enable or disable mp4 
checkout https://higheredlab.com/
