### ISSUE TITLE
small extension to make it work with valid_referers protection

### ISSUE THREAD

**Issue by dymitar** [manishkatyan/bbb-mp4#31]
In many cases the easiest way to protect the presentation from public access is to use valid_referers in nginx configuration.
But this makes the app not working.
There is an easy fix for this, adding a line to bbb-mp4.js:

page.setExtraHTTPHeaders({ referer: 'https://referer.taken.from.env/' });

The referer can be an additional argument, or using the same argument like for url

**Comment by arun-hel** [comment]
Thanks, We will check this.
