### ISSUE TITLE
Download Button gone after Update BBB 2.3.4 -> 2.3.6

### ISSUE THREAD

**Issue by roman-suru** [manishkatyan/bbb-mp4#32]
Greetings, thank you for this awesome tool.

My download button is gone since that update.
But also there is no 404 error for the mp4 in the DevTools,
so I think the javascript is not checking for the file anymore.

Running `./bbb-mp4-install.sh` again does not help. Any ideas?

**Comment by arun-hel** [comment]
@BackfischHunter  restore default index.html `mv /var/bigbluebutton/playback/presentation/2.3/index_default.html /var/bigbluebutton/playback/presentation/2.3/index.html`
and rerun `./bbb-mp4-install.sh`

**Comment by roman-suru** [comment]
This didn't work for me because my index_default.html had somehow errors.
I had to  add 
`</script><script src="/playback/presentation/2.3/download-button.js"></script>` 
to 
`/var/bigbluebutton/playback/presentation/2.3/index.html`

Thanks for the help nonetheless 👍
