### ISSUE TITLE
Audio and Video is not in sync in mp4 video

### ISSUE THREAD

**Issue by iamsumesh** [manishkatyan/bbb-mp4#37]
Audio and Video is not in sync in mp4 video, but it is in sync in bigbluebutton original link. 
Any suggestion to fix this issue.

**Comment by arun-hel** [comment]
@iamsumesh can you tell us how much delay are you getting? we will look into it

**Comment by iamsumesh** [comment]
@arunkumar141997 . We are getting a 1 to 2 seconds delay. The latest version of bigbluebutton was installed in VM.

**Comment by jbmarin** [comment]
I'm also trying to convert video but doesn't seem to work.
Its seems that we cannot access to bbb-mp4 docker image :


```
root@bbb:/var/www/bbb-mp4# docker pull bbb-mp4
Using default tag: latest
Error response from daemon: pull access denied for bbb-mp4, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

```
