### ISSUE TITLE
how to use with scalelite?

### ISSUE THREAD

**Issue by mohammad362** [manishkatyan/bbb-mp4#39]
How to use bbb-mp4 with scalelite?

**Comment by arun-hel** [comment]
Hi @mohammad362  

- Install bbb-mp4 on each bbb-server
- Make sure all bbb-mp4  will keep mp4 at one common place ( You can use nfs mounting ). change COPY_TO_LOCATION in .env
for example COPY_TO_LOCATION=`/mnt/scalelite-recordings/var/bigbluebutton/mp4`
- Copy index.html and download-button.js  from any bbb server where you have bbb-mp4 installed  to scalelite server
index.html location in bbb server :` /var/bigbluebutton/playback/presentation/2.3/index.html`
download-button.js location in bbb server  : `/var/bigbluebutton/playback/presentation/2.3/download-button.js`
- Create a file mp4_recording.nginx on scalelite server with below code, 
```
location /mp4 {
    root   /var/www/bigbluebutton-default;
    index  index.html index.htm;
    expires 1m;
}
``` 
-  Mount all those files and mp4 folder to scalelite nginx container
Add below lines  to nginx container's volume section (please change the files locations as per your setup)

```
   
        # Mp4 files mounting to  nginx container 
        - /mnt/scalelite-recordings/var/bigbluebutton/mp4/:/var/www/bigbluebutton-default/mp4/
        # mp4 playback support
        - ./bbb-mp4/mp4_recording.nginx:/etc/bigbluebutton/nginx/mp4_recording.nginx
        - ./bbb-mp4/playback/index.html:/var/bigbluebutton/playback/presentation/2.3/index.html
        - ./bbb-mp4/playback/download-button.js:/var/bigbluebutton/playback/presentation/2.3/download-button.js


```

**Comment by mohammad362** [comment]
> Hi @mohammad362
> 
>     * Install bbb-mp4 on each bbb-server
> 
>     * Make sure all bbb-mp4  will keep mp4 at one common place ( You can use nfs mounting ). change COPY_TO_LOCATION in .env
>       for example COPY_TO_LOCATION=`/mnt/scalelite-recordings/var/bigbluebutton/mp4`
> 
>     * Copy index.html and download-button.js  from any bbb server where you have bbb-mp4 installed  to scalelite server
>       index.html location in bbb server :` /var/bigbluebutton/playback/presentation/2.3/index.html`
>       download-button.js location in bbb server  : `/var/bigbluebutton/playback/presentation/2.3/download-button.js`
> 
>     * Create a file mp4_recording.nginx on scalelite server with below code,
> 
> 
> ```
> location /mp4 {
>     root   /var/www/bigbluebutton-default;
>     index  index.html index.htm;
>     expires 1m;
> }
> ```
> 
>     * Mount all those files and mp4 folder to scalelite nginx container
>       Add below lines  to nginx container's volume section (please change the files locations as per your setup)
> 
> 
> ```
>    
>         # Mp4 files mounting to  nginx container 
>         - /mnt/scalelite-recordings/var/bigbluebutton/mp4/:/var/www/bigbluebutton-default/mp4/
>         # mp4 playback support
>         - ./bbb-mp4/mp4_recording.nginx:/etc/bigbluebutton/nginx/mp4_recording.nginx
>         - ./bbb-mp4/playback/index.html:/var/bigbluebutton/playback/presentation/2.3/index.html
>         - ./bbb-mp4/playback/download-button.js:/var/bigbluebutton/playback/presentation/2.3/download-button.js
> ```

thanks, i test and report

**Comment by mohammad362** [comment]
Thanks, Worked Perfectly!
