### ISSUE TITLE
Change of presentation/playback URL

### ISSUE THREAD

**Issue by jamestombs** [manishkatyan/bbb-mp4#4]
The new updates over the weekend are great and have made what we were looking to do much simpler so thank you.

One thing that has changed though is the ease of being able to change the presentation that's recorded. By default it's using /2.0/ presentation, with the previous script we copied /2.0/ into our own presenation/playback with the chat stripped out and a few more changes so that we could change the layout of the resulting video.

Is it possible to make the URL that's recorded in the video an item in .env like it was before?

Also, not sure if this is a common issue but on the initial run of bbb-mp4-install.sh, apt complained that it couldn't find google-chrome-stable, I ran apt install google-chrome-stable after it finished and it installed without a problem. I then re-ran the bbb-mp4-install.sh script which went through and picked up ffmpeg which looks like it didn't install properly first time either. This was on an updated Ubuntu 16.04.7 server.

**Comment by jamestombs** [comment]
Follow up to this. So looks like for the latter if we copy the original playback.html to playback.ours.html and make changes to that, we can then set that in .env which is fine for bbb-mp4.js but bbb-mp4.sh is looking at playback.html regardless so it always fails.

Also, a secondary affect of running the bbb-mp4-install.sh twice results in the original playback.html file being overwritten by the redirect twice, so best to check for existence of playback.html.default before doing backup to avoid overriding the original file.

**Comment by manishkatyan** [comment]
Hi James,

Thanks for feedback. 

Added:
 - Check for pre-existing playback.html.default so that original BBB playback.html is not replaced in case you execute bbb-mp4-install.sh again
 - Now bbb-mp4.js uses playback_default.html to record a session. Redirect logic to send users to /recording uses playback.html. 
 
 Hope this solves both the issues you mentioned.

**Comment by jamestombs** [comment]
Yep, that looks like it will solve the issues.

**Comment by manishkatyan** [comment]
Closing.
