### ISSUE TITLE
Using on already MP4 Enabled server? 

### ISSUE THREAD

**Issue by morexzamani** [manishkatyan/bbb-mp4#40]
Hi
Thanks for your useful script. I have a question:

I've already enabled MP4 video and disabled WEBM format in `/usr/local/bigbluebutton/core/scripts/presentation.yml` 
Can I use your script on my server? Will duplicate mp4 files be created?

**Comment by arun-hel** [comment]
@MrCapitalist You can use bbb-mp4. bbb-mp4 converts your bbb recording into single mp4 file.

**Comment by morexzamani** [comment]
Thanks
I know, but my records already are mp4!
When I use bbb-mp4, 2 files create for playback? one of them is for online playback and another one is for download. Is it right?
Is it require more hard disk space?

**Comment by manishkatyan** [comment]
Can you play the mp4 and see what all it captures? Is it having
presentation and other items on it?

**Comment by morexzamani** [comment]
No, It contains webcam only. So I can use this script as a separate functionality
Thanks
