### ISSUE TITLE
Integrate with Scalelite Playback

### ISSUE THREAD

**Issue by morexzamani** [manishkatyan/bbb-mp4#41]
Hi
I want to use your script with the Scalelite load balancer. It means when the user uses the Scalelite playback page, it has a download link on it.

I think it can be deployed in 2 ways:

1- Offline mp4 (bbb-mp4) is made on BBB server and transferred to the Scalelite
2- Offline mp4 (bbb-mp4) is made on Scalelite after transfer videos to it

How can I do this?

**Comment by arun-hel** [comment]
This has been already dissussed here #39
