### ISSUE TITLE
installed on 2.3 successfully but not working

### ISSUE THREAD

**Issue by szekster** [manishkatyan/bbb-mp4#49]
recording do not seem to be converted after the meeting ends.   Are there logs that can be checked to find out what's broken?  any other trouble shooting tips?

**Comment by arun-hel** [comment]
@szekster  In BBB 2.3, BBB was using trollop gem to parse the commands, But in the latest version of BBB they are using the optimist gem,  So we updated the bbb mp4 to support the latest version of bbb.

Here is the workaround for bbb 2.3

1. Open `/usr/local/bigbluebutton/core/scripts/post_publish/bbb_mp4.rb`
2. Replace `require "optimist"` with `require "trollop"`
3. Replace `opts = Optimist::options do` with `opts = Trollop::options do`

Here is the complete file of bbb_mp4.rb for bbb 2.3: https://github.com/manishkatyan/bbb-mp4/blob/bb50e0d7f06f61494b692ba90edc5d41832840b9/bbb_mp4.rb

**Comment by szekster** [comment]
Thanks!
