### ISSUE TITLE
Add check for mp4 recording

### ISSUE THREAD

**Issue by jamestombs** [manishkatyan/bbb-mp4#5]
We're looking at adding this on to an existing installation of BBB which already has recordings. 

Going to playback.html always redirects, is it possible to add a check to see if the mp4 file exists first, if it doesn't then direct the user to playback_default.html?

The alternative is to manually run all previous saved recordings but that will take a long time as there are hundreds of recordings some of which are over 6 hours long.

**Comment by manishkatyan** [comment]
Hi James,

Checking for existence of MP4 video before redirecting is a good idea. We will take up this feature later this week. @arunkumar141997

**Comment by manishkatyan** [comment]
@jamestombs we liked this feature so much that we just implemented! Please try it out and thanks for your feedback!
