### ISSUE TITLE
Convert Old Recording and No Raw Files Exist 

### ISSUE THREAD

**Issue by uozbek** [manishkatyan/bbb-mp4#51]
I have many recordings has no raw files. Your project needs to the raw file, and after the recordings are finished scripts run and convert a single mp4 file. But I want to convert mp4 with my recordings link such as https://bbbtest.com//playback/presentation/2.3/xyz-123. Could I use your project as I said.

**Comment by arun-hel** [comment]
You can use it,

You can manually convert old recordings by executing `bbb-mp4.sh <recording Id>`

1. [Install](https://github.com/manishkatyan/bbb-mp4#install) bbb-mp4 
2. Go to bbb-mp4 directory
3. Run `bash bbb-mp4.sh <recording Id>`

In your case `bash bbb-mp4.sh  xyz-123`

**Comment by uozbek** [comment]
Thank you so much. It worked.
