### ISSUE TITLE
Add user to docker group instead of sudo

### ISSUE THREAD

**Issue by mmaridev** [manishkatyan/bbb-mp4#54]
I don't get it why would you have the `bigbluebutton` user run **any** command via sudo passwordless.
If, as it seems to be, you just need to create docker containers you can simply add the user to the `docker` group.
Will test this shortly.

**Comment by arun-hel** [comment]
@mmaridev we are working on it.

**Comment by arun-hel** [comment]
fixed in #55

**Comment by mmaridev** [comment]
Well done! Kudos for the project :-)
