### ISSUE TITLE
The bbb-mp4-install.sh installation script does not create the recording folder

### ISSUE THREAD

**Issue by fa305757** [manishkatyan/bbb-mp4#57]
Hello, in the meantime I would like to thank you for this very useful tool for converting BBB recording to MP4, there are some small issues that I noticed while installing the script:
the recording folder in /var/www/bigbluebutton-default/ is not created automatically and must be created manually.
Also I would like to ask you how you can change the video resolution of the generated MP4 file.
I thank you in advance for whatever you can tell me.
Best regards
John

**Comment by arun-hel** [comment]
@fa305757 recording folder in /var/www/bigbluebutton-default/  will be automatically created if it doesn't exist during the mp4 conversion

currently bbb-mp4 dont have option to change resolution. But you can modify [bbb-mp4.js](https://github.com/manishkatyan/bbb-mp4/blob/main/bbb-mp4.js#L10) and rebuild the docker image to change resolution.

Dont forget to update the docker image name in [bbb-mp4.sh](https://github.com/manishkatyan/bbb-mp4/blob/main/bbb-mp4.sh#L17)
