### ISSUE TITLE
Docker image doesn't work

### ISSUE THREAD

**Issue by nvducict** [manishkatyan/bbb-mp4#59]
After run 'manishkatyan/bbb-mp4' ends then '/var/www/bigbluebutton-default/recording' is empty

**Comment by kashifsaeed79** [comment]
face the same issue in fresh installation. I already install bbb-mp4 many times in past and it work without error. but now docker container not start its work.

**Comment by arun-hel** [comment]
We have updated the docker image, as well as few files. Pull the latest code  and latest docker image

```sh
cd /var/www/bbb-mp4
git pull
docker pull manishkatyan/bbb-mp4
```

If you  are still facing the issue. Try manually running bbb-mp4.sh and get the logs from the container.

```sh
cd /var/www/bbb-mp4
bash bbb-mp4.sh <recording_id> && docker logs <recording_id> -f
```

**Comment by nvducict** [comment]
Good job! Thanks the author
