### ISSUE TITLE
Stand BBB + Scalelite + Greenlight

### ISSUE THREAD

**Issue by AleksandrMikoshi** [manishkatyan/bbb-mp4#60]
Hello
We have a stand deployed according to this instruction - https://github.com/unistra/bigbluebutton/

Available:
2 BigBlueButton servers
1 server Scalelite balancer
1 greenlight server

NFS mount point deployed on Scalelite server

If possible, please tell me - how can a converter to mp4 be built into this circuit?
![BigBlueButton](https://user-images.githubusercontent.com/79300692/225552885-a704a9e3-9d2f-4839-9fc3-f6e3a1dbe2e3.png)

**Comment by arun-hel** [comment]
@AleksandrMikoshi You can try the following method
1. Install bbb-mp4 on each bbb servers
2. Create a shared nfs  volume for mp4 and update the `COPY_TO_LOCATION` env variable on each bbb server(`/var/www/bbb-mp4/.env`).
3. Modify the scalelite recordings playback container to serve the mp4 recording from shared nfs volume.
4. Modify the recording playback  container on scalelite to show download button.

**Comment by arun-hel** [comment]
@AleksandrMikoshi Were you able to resolve the issue with my solution above? If not, check-out our tech support plan - https://higheredlab.com/bigbluebutton-support/
