### ISSUE TITLE
Compatibility with BBB 2.6?

### ISSUE THREAD

**Issue by Shaalam3** [manishkatyan/bbb-mp4#61]
Hi, I am successfully using this mp4 download script in BBB 2.4 version. Thanks for this script. Recently I created a all new install of BBB 2.6 in AWS EC2 instance and also installed this bbb-mp4 script. When a meeting is completed, the download button is not shown in the default playback link (I am using Greenlight Version 3). 

But on seeing the /var/www/bigbluebutton-default/recording folder in FileZilla, the mp4 file is created and able to be downloaded through file zilla. The issue is the download button is not showing in the default playback url and also on accessing, 
https://<<bbb domain name>>/recording/meeting-id.mp4 is not loading that video. But I am able to see that video in file zilla for that specific meeting that too with the same meeting id file name. Is there any compatibility issue with recent BBB 2.6 or Am I missing anything? Kindly help in this regard.

**Comment by ofudre** [comment]
HI @Shaalam3 , in BBB 2.6 you have to use path "/var/www/bigbluebutton-default/assets/recording/" instead "/var/www/bigbluebutton-default/recording/" in your .env file. If you already made mp4 videos in /var/www/bigbluebutton-default/recording/ just move recording folder to /var/www/bigbluebutton-default/assets/ and everything should gonna be fine.

Have a nice day.

**Comment by arun-hel** [comment]
@Shaalam3 We are yet to update bbb-mp4 to support bbb 2.6. Mean while you can follow the workaround suggested by @ofudre to install and use bbb-mp4 on your bbb 2.6 server.

**Comment by Shaalam3** [comment]
@ofudre It worked perfectly. Thank you so much. @arun-hel Thanks for your reply.
