### ISSUE TITLE
Problema no acesso público dos arquivos mp4 gerados

### ISSUE THREAD

**Issue by JadsonLucena** [manishkatyan/bbb-mp4#65]
Estou usando a versão 2.6.8 do bbb
Em um linux: Canonical, Ubuntu, 20.04 LTS, amd64

Ao tentar acessar os arquivos mp4 gerados pela url: `https://<your-bbb-fqdn>/recording/<meeting_id>.mp4`
Me deparava com o HTTP ERROR 406 persistentemente

Para resolver, executei os seguintes comandos:
```bash
cd /usr/share/bigbluebutton/nginx
sudo touch bbb-mp4.nginx
sudo bash -c "echo 'location /recording { root    /var/www/bigbluebutton-default; }' > bbb-mp4.nginx"
sudo systemctl reload nginx
```

> É necessário se atentar que o caminho do root no arquivo bbb-mp4.nginx deve ser o mesmo do COPY_TO_LOCATION contido no arquivo /var/www/bbb-mp4/.env

**Comment by arun-hel** [comment]
@JadsonLucena  Thanks for the suggestion. We will add this to installation section.
