### ISSUE TITLE
Mp4 recording not working automatically

### ISSUE THREAD

**Issue by Moh23ce** [manishkatyan/bbb-mp4#7]
Hello guys, 
Thank you very much for the nice project. 
I followed the installation instructions, but here what is happening:
1- Start the meeting > start the recording > end the meeting.
2- tail -f /var/log/bigbluebutton/post_publish.log

I, [2021-02-17T18:14:52.654513 #26989]  INFO -- : Task: Getting meeting metadata
I, [2021-02-17T18:14:52.675215 #26989]  INFO -- : MP4 conversion started ID : true
I, [2021-02-17T18:14:53.148714 #26995]  INFO -- : Task: Getting meeting metadata
I, [2021-02-17T18:14:53.164974 #26995]  INFO -- : Recording Ready Notify for [ID] starts
I, [2021-02-17T18:14:53.165110 #26995]  INFO -- : Recording Ready notify ends

3- nothing is showing in the directory: /var/www/bigbluebutton-default/recording 

I should start the process manually by using the command below:
1. node bbb-mp4.js https://bbb-fqdn/playback/presentation/2.0/playback.html?meetingId=ID
2. ./bbb-mp4.sh ID
to be able to see the mp4 files.

**I am expecting all process will be working automatically, can you please help to figure out what is wrong here.**

**Comment by manishkatyan** [comment]
Hi,

Have you installed using bbb-mp4-install.sh [as detailed here](https://github.com/manishkatyan/bbb-mp4#install)?
If yes, meeting would get automatically converted into MP4.

You don't need to do step 1 or 2 that you mentioned. bbb-mp4.sg would get called by post-publish.rb, after a recording is published. 

May be your recording is still getting published or getting converted. Can you check after some time (few hours)?

If your meeting is published, it should be visible here: https://bbb-fqdn/playback/presentation/2.0/playback.html?meetingId=ID

Once published, MP4 should get converted in (meeting_duration + some more time). 

Let me know if you still face difficulties after waiting for publishing/conversion to get over.

**Comment by Moh23ce** [comment]
I reviewed the installation steps again, but I am still not able to get the it done.
I will remove everything and start over again.

I noticed one thing in some meeting, it keep redirecting to the HigherEdLab.com!

![Screenshot from 2021-02-18 09-48-16](https://user-images.githubusercontent.com/37180568/108316810-75e3d800-71ce-11eb-9162-35d6e819dea5.png)

**Comment by arun-hel** [comment]
Hi @Moh23ce , Have you done this?
```
# give bigbluebutton user sudo access
usermod -aG sudo bigbluebutton

# make sudo access passwordless
sudo visudo
# add the following line at the end of the file
bigbluebutton ALL=(ALL) NOPASSWD: ALL
```

**Comment by Moh23ce** [comment]
Hello @arunkumar141997, 

Yes I did all steps and repeated it over again.
I am still in the same situation.
Thank you guys for your efforts.
You may close the issue, as it might be coming from my dev environment.

**Comment by manishkatyan** [comment]
@Moh23ce Can you please try the latest code? 

We have simplified playback.html by redirecting after the page loads. So it should work in all cases.

**Comment by mcasycula87** [comment]
Hi @manishkatyan 
Thank you very much for the nice project.
I followed the installation instructions, but here what is happening:
/var/www/bbb-mp4/webm/.webm: No such file or directory

Let me know
Thanks in advance

**Comment by manishkatyan** [comment]
@Moh23ce Have to done this - cp .env-example .env

If you still face issues, I can look at your BBB server setup. Send me a private message at manishkatyan   @   gmail   .   com (email without spaces).

**Comment by nzmhtpgl** [comment]
i have the same problem.
I, [2021-03-20T21:36:08.066568 #19164]  INFO -- : Task: Getting meeting metadata
I, [2021-03-20T21:36:08.068041 #19164]  INFO -- : MP4 conversion started for 7607e7260f66a3d4390e866d32c3e3ebba698947-1616275825172: true
I, [2021-03-20T21:36:08.958849 #19289]  INFO -- : Task: Getting meeting metadata
I, [2021-03-20T21:36:08.959422 #19289]  INFO -- : Recording Ready Notify for [7607e7260f66a3d4390e866d32c3e3ebba698947-1616275825172] starts
I, [2021-03-20T21:36:08.959471 #19289]  INFO -- : Recording Ready notify ends
I, [2021-03-20T21:36:09.246636 #19301]  INFO -- : Recording transferring to Scalelite starts
I, [2021-03-20T21:36:09.247729 #19301]  INFO -- : Transferring recording for 7607e7260f66a3d4390e866d32c3e3ebba698947-1616275825172 to Scalelite
I, [2021-03-20T21:36:09.247975 #19301]  INFO -- : Found recording format: presentation/7607e7260f66a3d4390e866d32c3e3ebba698947-1616275825172
I, [2021-03-20T21:36:09.248003 #19301]  INFO -- : Creating recording archive
I, [2021-03-20T21:36:09.252541 #19301]  INFO -- : Transferring recording archive to /mnt/bbb-recordings
I, [2021-03-20T21:36:09.381607 #19301]  INFO -- : Recording transferring to Scalelite ends


when i run node bbb-mp4.js https://bbb/playback/presentation/2.0/playback.html?meetingId=xxx
Invalid recording URL! return. but when i click to link it opens the presentationlink correctly.

Anyway when i change the bbb-mp4.js link check regex then another error will throw:
Failed to launch the browser process! spawn /usr/bin/google-chrome ENOENT


Thanks in advance

**Comment by arun-hel** [comment]
@nzmhtpgl  Try our new updated code its fully dockerized. Also You can use` sh bbb-mp4.sh meetingID `for manual conversion (assuming you have created bbb-mp4:v1 docker image by running bbb-mp4-install.sh

**Comment by nzmhtpgl** [comment]
when i use sh bbb-mp4.sh 7607e7260f66a3d4390e866d32c3e3ebba698947-1616275825172 

there is an output : a336ca3ea0e9e3b0b524b46a3e44c14e9feb9bb2b7ea9c752eae68f71ee5e5d3
and there is no file in /var/www/bigbluebutton-default/recording/

this is last verison bbb-mp4:v1

**Comment by arun-hel** [comment]
@nzmhtpgl  run as sudo user, normal user might not have write access to that location.

**Comment by nzmhtpgl** [comment]
already run as sudo user

**Comment by arun-hel** [comment]
@nzmhtpgl  what does docker logs say?

**Comment by nzmhtpgl** [comment]
journalctl -fu docker.service
Mar 21 15:26:04 ip-10-1-15-48 dockerd[3088]: time="2021-03-21T15:26:04.642605223Z" level=info msg="ignoring event" container=1940975efe2db425d604a781009ee60152673bb9003923600ec2044c69b9acd5 module=libcontainerdnamespace=moby topic=/tasks/delete type="*events.TaskDelete"

**Comment by arun-hel** [comment]
@nzmhtpgl  when you run sh bbb-mp4.sh meetingID a container will be created with name as your meeting id . Then if you do docker logs MEETINGID -f you see the  logs related to bbb-mp4

**Comment by nzmhtpgl** [comment]
its output like this: Error: No such container: 7607e7260f66a3d4390e866d32c3e3ebba698947-1616275825172

 when i exec docker container ls it is empty also. i check docker images bbb-mp4       v1  is there.
when i run docker run bbb-mp4 id output is like that

Starting pulseaudio...
Waiting for pulseaudio to start...
URL undefined!

**Comment by arun-hel** [comment]
@nzmhtpgl  yeah its because docker run needs  some extra commands and env . You can see the docker run command in bbb-mp4.sh

**Comment by nzmhtpgl** [comment]
URL undefined! my bbb domain name  bbb.domain.**net** not **.com** . All the error could it be related to this?

**Comment by arun-hel** [comment]
That shouldn't  matter because we check url based on bbb domain name from .env
 Do you mind posting .env here?

**Comment by arunkumar141997** [comment]
@nzmhtpgl Do you mind posting .env here?

**Comment by nzmhtpgl** [comment]
playbackFile=playback_default.html
BBB_DOMAIN_NAME=vc-zfp7um.medixcall.net
COPY_TO_LOCATION=/var/www/bigbluebutton-default/recording

**Comment by arun-hel** [comment]
@nzmhtpgl `sudo docker run --rm --name bbb-mp4 -v /var/www/bigbluebutton-default/recording:/usr/src/app/download --env-file .env --env REC_URL=https://your.bbb.domain/playback/presentation/2.0/playback_default.html?meetingId=MEETING_ID bbb-mp4:v1`   Repalce MEETING_ID and your.bbb.domain with your meeting_id, domain and run this. Please choose small meeting, less than 5 minutes as above will run docker without -d (deamon mode). If possible provide me logs.

**Comment by nzmhtpgl** [comment]
Starting pulseaudio...
Waiting for pulseaudio to start...
PAGE LOG: ==Getting URL params
PAGE LOG: ==DOM content loaded
PAGE LOG: ==Resizing components
PAGE LOG: ==Resizing components
PAGE LOG: ==Resizing components
PAGE LOG: ==Resizing components
PAGE LOG: ==Resizing components
PAGE LOG: ==Resizing components
PAGE LOG: ==Resizing components
PAGE LOG: ==Resizing components
PAGE LOG: ==Processing metadata.xml
PAGE LOG: Failed to load resource: the server responded with a status of 404 (Not Found)
PAGE LOG: Failed to load resource: the server responded with a status of 404 (Not Found)
PAGE LOG: ==Found video /presentation/7607e7260f66a3d4390e866d32c3e3ebba698947-1616275825172/video/webcams.webm
PAGE LOG: ==Found deskshare /presentation/7607e7260f66a3d4390e866d32c3e3ebba698947-1616275825172/deskshare/deskshare.webm
PAGE LOG: ==Loading playback
PAGE LOG: ==Hide playback content
PAGE LOG: ==Loaded logo from logo.png
PAGE LOG: ==Loading video
PAGE LOG: ==Loading acorn media player
PAGE LOG: ==Loading deskshare
PAGE LOG: ==Processing shapes.svg
PAGE LOG: ==Processing panzooms.xml
PAGE LOG: ==Processing cursor.xml
PAGE LOG: ==Processing deskshare.xml
PAGE LOG: ==Processing captions.json
PAGE LOG: Failed to load resource: the server responded with a status of 404 (Not Found)
PAGE LOG: ==Couldn't load presentation_text.json JSHandle@object
PAGE LOG: ==Processing slides.txt
PAGE LOG: ==All medias can be played
PAGE LOG: ==Linking chat to media
PAGE LOG: ==Running popcorn
PAGE LOG: 'webkitRequestAnimationFrame' is vendor-specific. Please use the standard 'requestAnimationFrame' instead.
PAGE LOG: ==Generating thumbnails
PAGE LOG: ==Setting title on thumbnails
PAGE LOG: ==Defining start time
PAGE LOG: ==Loading done
PAGE LOG: ==Show playback content
PAGE LOG: ==Resizing components
45.341
7607e7260f66a3d4390e866d32c3e3ebba698947-1616275825172
stderr: ffmpeg version 4.3.2-0york0~18.04 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version='0york0~18.04' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libzimg --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared

stderr:   libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100

stderr: [x11grab @ 0x559de1dcf3c0] Stream #0: not enough frames to estimate rate; consider increasing probesize

stderr: Input #0, x11grab, from ':102':
  Duration: N/A, start: 1616395941.617052, bitrate:
stderr: 983040 kb/s
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 1280x800, 983040 kb/s, 30 fps, 1000k tbr, 1000k tbn, 1000k tbc

stderr: Guessed Channel Layout for Input Stream #1.0 : stereo
Input #1, alsa, from 'pulse':
  Duration: N/A, start: 1616395942.502942, bitrate: 1536 kb/s
    Stream #1:0: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s

stderr: Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
  Stream #1:0 -> #0:1 (pcm_s16le (native) -> aac (native))
Press [q] to stop, [?] for help

stderr: [libx264 @ 0x559de1df9100]
stderr: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2

stderr: [libx264 @ 0x559de1df9100]
stderr: profile High, level 3.2

stderr: [libx264 @ 0x559de1df9100]
stderr: 264 - core 155 r2917 0a84d98 - H.264/MPEG-4 AVC codec - Copyleft 2003-2018 - http://www.videolan.org/x264.html - options: cabac=1 ref=1 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=2 psy=1 psy_rd=1.00:0.00 mixed_ref=0 me_range=16 chroma_me=1 trellis=0 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=0 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=1 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=10 rc=crf mbtree=1 crf=22.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00

stderr: Output #0, mp4, to '/usr/src/app/download/7607e7260f66a3d4390e866d32c3e3ebba698947-1616275825172.mp4':

stderr:   Metadata:
    encoder         : Lavf58.45.100

stderr:     Stream #0:0: Video: h264 (libx264) (avc1 / 0x31637661), yuv420p(progressive), 1280x800, q=-1--1, 30 fps, 15360 tbn, 30 tbc
    Metadata:
      encoder         : Lavc58.91.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
    Stream #0:1: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 128 kb/s
    Metadata:
      encoder         : Lavc58.91.100 aac

**Comment by arun-hel** [comment]
your mp4 should be present at `/var/www/bigbluebutton-default/recording` Is it present?

**Comment by arun-hel** [comment]
@nzmhtpgl  If you still have issue please make sure `/var/www/bigbluebutton-default/recording` directory is exist , check if the recording is available . Or  I can take a look at your bbb-mp4 setup if thats ok.

**Comment by nzmhtpgl** [comment]
ok it is presented as mp4. file created . but mp4 file is not playable. when i check its size 8.0kb. my presentation is about 30sec normally.

**Comment by arun-hel** [comment]
@nzmhtpgl  It happens because of multiple times trying to convert the same recording .To resolve this Remove that mp4 and re convert it using sh bbb-mp4.sh meeting id
I Hope your issue will solve.

**Comment by manishkatyan** [comment]
Closing as no response from the user
