### ISSUE TITLE
records were not visible on greenlight

### ISSUE THREAD

**Issue by ibrahimbilgin** [manishkatyan/bbb-mp4#8]
hi, i installed it on my server and it worked fine. However, when I installed it on another server, the records were not visible on greenlight. how should i go?

**Comment by arun-hel** [comment]
Hi @ibrahimbilgin , As we updated the default playback.html, when you would visit the default playback url - `https://<your-bbb-fqdn>/playback/presentation/2.0/playback.html?meetingId=<meeting_id>` - you would be redirected to the corresponding MP4 video url -` https://<your-bbb-fqdn>/recording/<meeting_id>.mp4`

**Comment by ibrahimbilgin** [comment]
> Hi @ibrahimbilgin , As we updated the default playback.html, when you would visit the default playback url - `https://<your-bbb-fqdn>/playback/presentation/2.0/playback.html?meetingId=<meeting_id>` - you would be redirected to the corresponding MP4 video url -` https://<your-bbb-fqdn>/recording/<meeting_id>.mp4`

yes I know but there is a problem with the redirect, also I cannot see my recordings on greenlight :( https://british.web.tr/playback/presentation/2.0/playback_default.html?meetingId=123123asd

**Comment by arun-hel** [comment]
> > Hi @ibrahimbilgin , As we updated the default playback.html, when you would visit the default playback url - `https://<your-bbb-fqdn>/playback/presentation/2.0/playback.html?meetingId=<meeting_id>` - you would be redirected to the corresponding MP4 video url -` https://<your-bbb-fqdn>/recording/<meeting_id>.mp4`
> 
> yes I know but there is a problem with the redirect, also I cannot see my recordings on greenlight :( https://british.web.tr/playback/presentation/2.0/playback_default.html?meetingId=123123asd

If you have followed installation steps it should work fine here is the sample [Sample Playback](https://cpp3.higheredlab.com/playback/presentation/2.0/playback.html?meetingId=bc42c8fb15da459aced61b05df785497eeaed36f-1613208131766) I dont have mp4 for this meeting ,so it is redirecting to default player.If i had mp4 for this meeting it would have redirected to `mydomain.com/recording/meetingid.mp4`.
you have mentioned it is working on one of your server, are you able to see the recordings of that server in greenlight?

**Comment by manishkatyan** [comment]
@ibrahimbilgin Can you please try the latest code? 

We have simplified playback.html by redirecting after the page loads. So it should work in all cases.

**Comment by ibrahimbilgin** [comment]
> @ibrahimbilgin Can you please try the latest code?
> 
> We have simplified playback.html by redirecting after the page loads. So it should work in all cases.

I want to install clean, how can I uninstall this tool?



> > > Hi @ibrahimbilgin , As we updated the default playback.html, when you would visit the default playback url - `https://<your-bbb-fqdn>/playback/presentation/2.0/playback.html?meetingId=<meeting_id>` - you would be redirected to the corresponding MP4 video url -` https://<your-bbb-fqdn>/recording/<meeting_id>.mp4`
> > 
> > 
> > yes I know but there is a problem with the redirect, also I cannot see my recordings on greenlight :( https://british.web.tr/playback/presentation/2.0/playback_default.html?meetingId=123123asd
> 
> If you have followed installation steps it should work fine here is the sample [Sample Playback](https://cpp3.higheredlab.com/playback/presentation/2.0/playback.html?meetingId=bc42c8fb15da459aced61b05df785497eeaed36f-1613208131766) I dont have mp4 for this meeting ,so it is redirecting to default player.If i had mp4 for this meeting it would have redirected to `mydomain.com/recording/meetingid.mp4`.
> you have mentioned it is working on one of your server, are you able to see the recordings of that server in greenlight?

no mp4 records not showing on "greenlight"

**Comment by manishkatyan** [comment]
To uninstall,

1. mv /var/bigbluebutton/playback/presentation/2.0/playback_default.html /var/bigbluebutton/playback/presentation/2.0/playback.html
2. mv /usr/local/bigbluebutton/core/scripts/post_publish/post_publish.rb.default /usr/local/bigbluebutton/core/scripts/post_publish/post_publish.rb

With this, you would be able to restore default playback behavior and default post_poublish action.

**Comment by ibrahimbilgin** [comment]
i uninstall it but i cant see my recording :(
this link -> https://british.web.tr/playback/presentation/2.0/playback.html?meetingId=8ae04156b98b6e8597de1416b4e153d40a18acd7-1613066383930 **redirecting to** -> https://british.web.tr/playback/presentation/2.0/playback_default.html?meetingId=8ae04156b98b6e8597de1416b4e153d40a18acd7-1613066383930 and its 404

**Comment by arun-hel** [comment]
@ibrahimbilgin perhaps the default playback.html file is changed. The content of your`/var/bigbluebutton/playback/presentation/2.0/playback.html` and this file: [playback.html](https://github.com/bigbluebutton/bigbluebutton/blob/develop/record-and-playback/presentation/playback/presentation/2.0/playback.html)  should match . If you uninstalled bbb-mp4 and the files content doesn't  match then replace your playback.html with the one i have mentioned earlier.

**Comment by ibrahimbilgin** [comment]
i still have the same problem. Although I did uninstall, it didn't improve.
https://british.web.tr/playback/presentation/2.0/playback_default.html?meetingId=8ae04156b98b6e8597de1416b4e153d40a18acd7-1613066383930

**Comment by arun-hel** [comment]
@ibrahimbilgin can you post your `playback.html` and `playback_default.html` code here?
